# -*- coding: utf-8 -*-
"""Quality Quest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LoUUL7npIdj_VzeP9nip0NOIFXkJLR7K

1. Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

"""2. Download the Data Directly from the Web"""

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
df = pd.read_csv(url, sep=';')

"""3. Explore Data"""

print(df.head())
print(df.info())
print(df.describe())

"""4. Exploratory Data Analysis (EDA)"""

sns.countplot(x='quality', data=df)
plt.title('Distribution of Wine Quality')
plt.show()

corr = df.corr()
plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Feature Correlation Heatmap')
plt.show()

"""5. Data Preparation"""

X = df.drop('quality', axis=1)
y = df['quality']

# Convert quality to binary: Good (1) if >=7, else Bad (0)
y = np.where(y >= 7, 1, 0)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""6. Train Multiple Models"""

models = {
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'KNN': KNeighborsClassifier(),
    'SVM': SVC()
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    results.append({
        'Model': name,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred),
        'Recall': recall_score(y_test, y_pred),
        'F1 Score': f1_score(y_test, y_pred)
    })

results_df = pd.DataFrame(results)
print(results_df)

"""7. Visualize Model Comparison"""

results_df.set_index('Model', inplace=True)
results_df.plot(kind='bar', figsize=(10,6))
plt.title('Model Performance Comparison')
plt.ylabel('Score')
plt.show()

"""**Conclusion:** Among the compared models — Decision Tree, Random Forest, KNN, and SVM — the Random Forest algorithm achieved the highest performance, making it the most reliable model for wine quality prediction."""

results_df.to_csv("model_comparison_results.csv", index=False)